name: build-and-test

on: [ push ]

jobs:
  Build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run tests
        run: ./gradlew -p mockposable test

      - name: Run integration tests
        run: ./gradlew test

#      - name: Cache AVD snapshot
#        uses: actions/cache@v3
#        id: avd-cache
#        with:
#          path: |
#            ~/.android/avd/*
#            ~/.android/adb*
#          key: avd-29-google-apis
#
#      - name: Create AVD and generate snapshot for caching
#        if: steps.avd-cache.outputs.cache-hit != 'true'
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          target: google_apis
#          arch: x86_64
#          profile: pixel
#          avd-name: Pixel_3a_API_29
#          force-avd-creation: false
#          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          disable-animations: true
#          script: echo "Generated AVD snapshot for caching"
#
#      - name: Run integration Android tests
#        uses: reactivecircus/android-emulator-runner@v2.27.0
#        with:
#          api-level: 29
#          target: google_apis
#          arch: x86_64
#          profile: pixel
#          avd-name: Pixel_3a_API_29
#          disable-animations: true
#          script: |
#            # adb logcat -c
#            # adb logcat *:E &
#            ./gradlew connectedCheck
